# Generated by Django 3.2.4 on 2021-07-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='english',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='maths',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='science',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='social',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='tamil',
            field=models.FloatField(),
        ),
    ]
